language: node_js
node_js:
- '10'
deploy:
  provider: npm
  email: michal.m.zarach@gmail.com
  skip_cleanup: true
  api_key:
    secure: mZmtYpgu/CJ5AISW+Ffcknbh4LAfmjRAB7SDdCN3wsUZTBw9oLNR8Acb3j4IpqI2d8riXtkXRVEF398LI+HiSuKat7FwB3y4RBRo1aotjQHfowpdd86Ym3eif/auleCbMYko1pgjLJZ8bKAfrMKwodnBbHcfrQ3+XpvVKT86dZfWwg8dFzJ7k2vhFgUZUhudc8+UkqdOFBYPw4Q4hhluzkBEVgIw3Z7kY0+XllQ5N8Fgpci6sbbKz7YT+fUQ/RSY8BxqSdsinMQ/ezktXHHKAOXQmzPNz4156S08kUwazGlhjpUYG1AnLK8FKyalQ2Nn5Z07mRMgmlEgJV/mjBiJWJWyL4MZ8iUpjMBnqGqFJkhGw3wUPxrdRSWM4GQN5JESCjPDp7znLUtzk9bj3L7GzMNF2wdWVfmLKskHiRXyNuUCNcvQ0+iOCjCNsC1hhD5EK5OkzPor/RWefzilFdOpHOWywaGz7JNyTL0VypW16Z0r25HrkIv83FjU0K/4Xn6tIS1u00pydBvHp+X9+hz3m8E2iKFlRAm7rNAnROYe+ZMfgeL9vAOlfofF9ek0G/zcMhYa3xg4DBv0lH5nODPun+QzqaoHwm3m6RfNVP+ufymkWVpKnW98IJ3LLjZVPrrTlFTrkYCcn1M8PeuZRVfVAnVn+thQ2VslkDUoZ/CKQqU=
  on:
    tags: true
    repo: michalzaq12/swagger-ts-codegen
    branch: master
