language: node_js
node_js:
- '10'
deploy:
  provider: npm
  email: michal.m.zarach@gmail.com
  skip_cleanup: true
  api_key:
    secure: Hek7CjFSs1tVbC7BpSvhmryMkVoXWZs2ZtpE0F7gQ9E3FWnRxHfIKoJ4W5OSgyiBDokOlfv/P5LXAu7IzLbL4alRPv1D9s9brPtSNupmaV/qPmYi3vyoVWBk+tSu1CAQb7lIF4Lx2sSFNyp+/zchUq5wlepen8Cd/rpevWNMGu2EgvsXmHh6Nkm+0V+nf3bBdpj6na9hiHGKTVefSlzJ63hJd+EbrdJBnKSlsHwsJRD6pjz2SRqXCvkyM+DxFfuH94WWeNfbUg9lLg2osOZd3z+DGE/0QejpWDsd/3gZqdXnno6jlx5xR0N0ij3M3D86OUu/1/MR/VZzCsiofKMxyoHak6Ofsu23v+U/OHAx/ebnL356y4YTt2H8ieltmtZR71YXvYTWRyNZITflbX8POIuYi5RgES0vdQdFxyQ1WRMYM5IltDayxqxTS6I20wHkJgj7BSbu5VcshmCbPgiDqRlyHblisImr54DynsxqbJX8sW0i6NDVITcr2v4wbCgIEjMpw56hNQv/UQkw2iWIUOry4upn2vzObphPUO9AL7ZqYniWW6M88Vwpa5M9KCZIdCvZx48P5TemIjLULgGQZAWt9TQmslZr8kaXfXAKbCrfEdR3OXZi4eKmCIOQQ5Z8i+8BscXt4+fwEAIBjMLcoUL40pTVfxskjZyIxIpfmKE=
  on:
    tags: true
    repo: michalzaq12/swagger-ts-codegen
    branch: master
